# backend/app/schemas/story.py

from pydantic import BaseModel, Field

class StoryRequest(BaseModel):
    """
    Defines the two-prompt input from the artisan.
    """
    artisan_heritage: str = Field(
        ...,
        description="Artisan's introduction and craft heritage.",
        examples=["I am a third-generation potter from Kutch, Gujarat."]
    )
    piece_story: str = Field(
        ...,
        description="The story or inspiration behind this specific art piece.",
        examples=["This vase is inspired by the monsoon clouds rolling over the Rann."]
    )

class StoryResponse(BaseModel):
    """
    Defines the polished story generated by the LLM.
    """
    generated_story: str = Field(
        ...,
        description="The final, polished narrative for the product listing."
    )